### ISSUE TITLE
Non-Existent Locality - National Coach

### ISSUE THREAD

**Issue by DIPAD-Andrew-Sharma-Vreshkova** [department-for-transport-public/naptanmapper#1]
* **Describe the bug**
The bug is caused by a National prefix (900) being non-existent in NaPTAN. This has been imported into the lookup_atco_codes() function using the dataframe local_area_lookup, however there is no associated data with it. The only National ATCO codes are 910, 920, 930, and 940

* **Tell us how to reproduce the error**

1. Run the App
2. Within the Input for "Select area to investigate", select 'National Coach'
3. The app will crash with a warning message:
"**Warning: Error in call_naptan: An atco area code provided does not exist. Please check your query. To display all valid atco codes, run lookup_atco_codes()**"

* **Expected behavior**

The expected behaviour of this input is not to display the national coach (ATCO 900) within a dropdown.

* **Platform**

Were you running the code on:

- [X] Your network laptop
- [ ] Citrix
- [X] Non-network laptop
- [ ] Other platform (please specify)

**Comment by Ellie-Glock** [comment]
I have had a look and the issue is that there are no National Coach (first three digits of Atco = 900) stops in the API. This is a NaPTAN issue not an issue with the app.
